name: food_delivery_app
description: A Trail Food Delivery app project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0 

  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  provider: ^4.3.2+1
  fluttertoast: ^8.0.8
  google_fonts: ^1.1.2
  simple_animations: ^1.3.3
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1

flutter_native_splash:
  color: "#DE781F"
  image: assets/images/splash_logo.png
  color_dark: "1a1a1a"
  image_dark: assets/images/splash_logo.png
  android: true
  ios: true
  
  #android_gravity: fill
  #iso_content_mode: scaleAspectFill


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/