name: food_delivery_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_native_splash:
  color: "#DE781F"
  image: assets/images/splash_logo.png
  color_dark: "1a1a1a"
  image_dark: assets/images/splash_logo.png
  android: true
  ios: true
  
  #android_gravity: fill
  #iso_content_mode: scaleAspectFill

flutter:

  uses-material-design: true

  assets:
      - assets/images/splash_logo.png
      - assets/images/
      - assets/icons/